Use Guzzle Directly for Localise instead of Loco SDK
26B/i18n-midoru pull request #21
Opened 2021-03-05 12:07 UTC by goncaloasimoes

Loco SDK (https://github.com/loco/loco-php-sdk) hides the responses from the api, except for the body, so we can't access the headers. It also doesn't let us introduce certain headers into the requests. In order to check for changes (see https://localise.biz/help/developers/api-rate#etag), we need to read/write these headers.

Here we just change from the SDK to use Guzzle directly.

2021-03-05 13:01 UTC, xipasduarte approved these changes

2021-03-08 16:33 UTC, csrui requested changes

2021-03-08 16:33 UTC, csrui commented on lib/Clients/Service/Localise.php
> +			'https://localise.biz/api/auth/verify',
Deves passar o `https://localise.biz/api/` como base_uri na instanciação do `Client`.

```suggestion
			'auth/verify',
```

2021-03-08 16:33 UTC, csrui commented on lib/Clients/Service/Localise.php
> +			'https://localise.biz/api/export/locale/%s.%s',
Após o base_uri actualizas este também.

```suggestion
			'export/locale/%s.%s',
```

2021-03-08 16:33 UTC, csrui commented on lib/Clients/Service/Localise.php
> +		$url  = sprintf( 'https://localise.biz/api/import/%s', $args['ext'] );
```suggestion
		$url  = sprintf( 'import/%s', $args['ext'] );
```

2021-03-08 16:33 UTC, csrui commented on lib/Clients/Service/Localise.php
> +		$url .= $this->get_query_string( $args );
Podes dispensar este método e usar o `http_build_query()`.

2021-03-09 12:09 UTC, csrui approved these changes

2021-03-09 12:11 UTC, merged